### PR TITLE
Upgrade PolicyReport CRD to v1beta1

### PR DESCRIPTION
**Pull request by zyjjay**
ref: https://issues.redhat.com/browse/ACM-7651

### CODE REVIEW

**Comment by zyjjay** [comment]
There's a lot of lines removed because of running `go mod tidy`

**Review by yiraeChristineKim — APPROVED** [review]

**Review by JustinKuli — APPROVED** [review]

**Comment by JustinKuli** [comment]
@dislbenn can you take a look at this? I think you have approval permissions here.

**Pull request merged**
