### PR TITLE
update go to 1.20

### PR DESCRIPTION
**Pull request by SherinV**
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>

### Description of changes
update go version to 1.20 
ioutil is deprecated. No longer works with go1.20. Update to io/os.
Updated response body close function to avoid vulnerability: Deferring unsafe method "Close" on type "io.ReadCloser"

### CODE REVIEW

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

**Comment by SherinV** [comment]
/override sonar-pre-submit
PR to move project to go1.20 and overcome gosec vulnerabilities.

**Pull request merged**
