### PR TITLE
 fixed return to not to exit the loop

### PR DESCRIPTION
**Pull request by xrajesh**
Signed-off-by: xavier dharmaiyan <xavier@redhat.com>

**Related Issue:**  [open-cluster-management/backlog#<ISSUE_NUMBER>
](https://github.com/stolostron/backlog/issues/19407)

### CODE REVIEW

**Review by willkutler — APPROVED** [review]

**Comment by crizzo71** [comment]
@smithbw88 Adding this to 2.4.3 RC2 @evelinec this address the regression raised today

**Pull request merged**
