### PR TITLE
[release-2.8] Manual cherry-pick to handle non-OCM policy types (#143, #150)

### PR DESCRIPTION
**Pull request by dhaiducek**
**Related Issues:**

- https://issues.redhat.com/browse/ACM-6350
- https://issues.redhat.com/browse/ACM-7264

Replaces:
- #145 

Cherry-picks:
- #143 
- #150 
- #152 
- #153

### CODE REVIEW

**Review by jlpadilla — APPROVED** [review]
/lgtm
/hold

**Comment by dhaiducek** [comment]
/unhold

@jlpadilla Would you please re-review this PR?

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Pull request merged**
